name = "blog-lwtdzh"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "blog-lwtdzh"
database_id = "95321313-2b28-4a20-a506-4d594fab6593"
