/**
 * Build-time script: scans content/posts/*.md, parses front-matter,
 * and generates src/generated/articles.ts with all article data bundled in.
 * 
 * Usage: npx tsx scripts/build-articles.ts
 */

import * as fs from 'fs';
import * as path from 'path';

interface FrontMatter {
  title: string;
  date: string;
  updated?: string;
  slug: string;
  tags: string[];
  description?: string;
  cover?: string;
  hidden?: boolean;
}

function parseFrontMatter(fileContent: string): { data: FrontMatter; content: string } {
  const match = fileContent.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) {
    throw new Error('No front matter found');
  }

  const yamlStr = match[1];
  const content = match[2].trim();

  const data: any = {};
  const lines = yamlStr.split('\n');

  for (const line of lines) {
    const colonIdx = line.indexOf(':');
    if (colonIdx === -1) continue;

    const key = line.substring(0, colonIdx).trim();
    let value = line.substring(colonIdx + 1).trim();

    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    if (key === 'tags') {
      try { data.tags = JSON.parse(value); } catch { data.tags = []; }
    } else if (key === 'hidden') {
      data.hidden = value === 'true';
    } else {
      data[key] = value;
    }
  }

  return { data: data as FrontMatter, content };
}

function escapeForTemplate(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
}

function main() {
  const postsDir = path.join(process.cwd(), 'content', 'posts');
  const outDir = path.join(process.cwd(), 'src', 'generated');
  const outFile = path.join(outDir, 'articles.ts');

  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  const files = fs.readdirSync(postsDir).filter(f => f.endsWith('.md'));
  const articles: { data: FrontMatter; content: string; filename: string }[] = [];

  for (const file of files) {
    const filePath = path.join(postsDir, file);
    const raw = fs.readFileSync(filePath, 'utf-8');
    try {
      const { data, content } = parseFrontMatter(raw);
      articles.push({ data, content, filename: file });
    } catch (e) {
      console.error(`ERROR processing ${file}: ${e}`);
    }
  }

  // Sort by date descending
  articles.sort((a, b) => b.data.date.localeCompare(a.data.date));

  let output = `// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by scripts/build-articles.ts from content/posts/*.md
// Run: npx tsx scripts/build-articles.ts

export interface ArticleData {
  slug: string;
  title: string;
  date: string;
  updated: string;
  description: string;
  tags: string[];
  cover: string;
  hidden: boolean;
  content: string;
}

export const articles: ArticleData[] = [\n`;

  for (const article of articles) {
    const d = article.data;
    output += `  {
    slug: ${JSON.stringify(d.slug)},
    title: ${JSON.stringify(d.title)},
    date: ${JSON.stringify(d.date)},
    updated: ${JSON.stringify(d.updated || d.date)},
    description: ${JSON.stringify(d.description || '')},
    tags: ${JSON.stringify(d.tags || [])},
    cover: ${JSON.stringify(d.cover || '')},
    hidden: ${d.hidden ? 'true' : 'false'},
    content: \`${escapeForTemplate(article.content)}\`,
  },\n`;
  }

  output += `];\n`;

  fs.writeFileSync(outFile, output, 'utf-8');
  console.log(`Generated ${outFile} with ${articles.length} articles`);
}

main();
