/**
 * Build-time script: scans content/posts/*.md, parses front-matter,
 * and generates src/generated/articles.ts with all article data bundled in.
 * 
 * Usage: npx tsx scripts/build-articles.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { type ArticleFrontMatter, parseArticleFile } from '../src/lib/article-files';

function escapeForTemplate(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
}

function main() {
  const postsDir = path.join(process.cwd(), 'content', 'posts');
  const outDir = path.join(process.cwd(), 'src', 'generated');
  const outFile = path.join(outDir, 'articles.ts');

  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  const files = fs.readdirSync(postsDir).filter(f => f.endsWith('.md'));
  const articles: { data: ArticleFrontMatter; content: string; filename: string }[] = [];

  for (const file of files) {
    const filePath = path.join(postsDir, file);
    const raw = fs.readFileSync(filePath, 'utf-8');
    try {
      const { data, content } = parseArticleFile(raw);
      articles.push({ data, content, filename: file });
    } catch (e) {
      console.error(`ERROR processing ${file}: ${e}`);
    }
  }

  // Sort by date descending
  articles.sort((a, b) => b.data.date.localeCompare(a.data.date));

  let output = `// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by scripts/build-articles.ts from content/posts/*.md
// Run: npx tsx scripts/build-articles.ts

export interface ArticleData {
  slug: string;
  title: string;
  date: string;
  updated: string;
  description: string;
  tags: string[];
  cover: string;
  hidden: boolean;
  content: string;
}

export const articles: ArticleData[] = [\n`;

  for (const article of articles) {
    const d = article.data;
    output += `  {
    slug: ${JSON.stringify(d.slug)},
    title: ${JSON.stringify(d.title)},
    date: ${JSON.stringify(d.date)},
    updated: ${JSON.stringify(d.updated || d.date)},
    description: ${JSON.stringify(d.description || '')},
    tags: ${JSON.stringify(d.tags || [])},
    cover: ${JSON.stringify(d.cover || '')},
    hidden: ${d.hidden ? 'true' : 'false'},
    content: \`${escapeForTemplate(article.content)}\`,
  },\n`;
  }

  output += `];\n`;

  fs.writeFileSync(outFile, output, 'utf-8');
  console.log(`Generated ${outFile} with ${articles.length} articles`);
}

main();
